name: Release CI

permissions:
  contents: read
  packages: read  

on:
  pull_request:
  workflow_dispatch:
    inputs:
      send_telegram:
        description: "Release to Telegram"
        required: true
        default: false
        type: boolean
      send_github:
        description: "Release on GitHub"
        required: true
        default: false
        type: boolean
      send_playstore:
        description: "Release on Play Store"
        required: true
        default: false
        type: boolean
      playstore_track:
        type: choice
        default: production
        description: Google Play Store Track
        options:
        - production
        - beta
        - alpha
        - qa

jobs:
  # Build step for both official & spoofed flavors
  build-release:
    runs-on: ubuntu-latest
    name: Build Matrix
    strategy:
      fail-fast: false
      matrix:
        flavor: [official, spoofed]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build APK
        id: build-apk
        uses: ./.github/actions/build-apk
        with:
          username: ${{ secrets.ACTOR }}
          token: ${{ secrets.GH_TOKEN }}
          flavor: ${{ matrix.flavor }}
          buildType: "release"
          keyStore: ${{ secrets.KEY_STORE }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

  # Release to Telegram
  release-telegram:
    if: github.event.inputs.send_telegram == 'true'
    name: Release to Telegram
    needs: build-release
    uses: ./.github/workflows/telegram.yml
    secrets: inherit

  # Release to GitHub
  release-github:
    if: github.event.inputs.send_github == 'true'
    name: Release to GitHub
    needs: build-release
    uses: ./.github/workflows/github.yml
    secrets: inherit

  # Release to Play Store
  release-playstore:
    if: github.event.inputs.send_playstore == 'true'
    name: Release to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up signing key
        run: |
          if [ -n "${{ secrets.KEY_STORE }}" ]; then
              echo keyStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> signing.properties
              echo keyAlias='${{ secrets.KEY_ALIAS }}' >> signing.properties
              echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> signing.properties
              echo keyStore='${{ github.workspace }}/key.jks' >> signing.properties
              echo ${{ secrets.KEY_STORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
          
      - name: Set up credentials for private packages
        shell: bash
        run: |
          [ -f gradle.properties ] && [ "$(tail -c1 gradle.properties)" != "" ] && echo >> gradle.properties
          {
            echo "gpr.user=${{ inputs.username }}"
            echo "gpr.key=${{ inputs.token }}"
          } >> gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Bundle with Gradle
        run: chmod +x ./gradlew && ./gradlew bundleOfficialPlaystore

      - name: Find AAB
        id: find_aab
        run: |
          AAB_PATH=$(find app/build/outputs/bundle/officialPlaystore -name "*.aab" -print -quit)
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_OUTPUT

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.dergoogler.mmrl
          releaseFiles: ${{ steps.find_aab.outputs.AAB_PATH }}
          track: ${{ github.event.inputs.playstore_track }}
          status: completed
          inAppUpdatePriority: 5







